/* PROJECT: ZEYAD LMS (Single Instructor)
  TYPE: Production Schema
  FEATURES: Direct Codes, Bundles, Device Lock, Progress Tracking
*/

-- =============================================
-- 1. EXTENSIONS & UTILS
-- =============================================
-- تفعيل الامتدادات الضرورية
create extension if not exists "uuid-ossp";

-- دالة لتحديث التوقيت تلقائياً
create or replace function update_updated_at_column()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language 'plpgsql';

-- =============================================
-- 2. USERS & SECURITY (المستخدمين وحماية الأجهزة)
-- =============================================

-- جدول بيانات المستخدمين الإضافية
create table public.profiles (
  id uuid references auth.users(id) on delete cascade primary key,
  full_name text not null,
  phone_number text,
  academic_year text, -- السنة الدراسية (3 ثانوي، إلخ)
  role text check (role in ('admin', 'student', 'teacher')) default 'student',
  is_banned boolean default false,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- جدول بصمة الأجهزة (لمعرفة عدد الأجهزة لكل طالب)
create table public.student_devices (
  id bigint generated by default as identity primary key,
  student_id uuid references public.profiles(id) on delete cascade,
  device_id text not null, -- Unique ID from Expo Application
  device_name text, -- e.g. "Samsung S21"
  last_active timestamp default now(),
  created_at timestamp default now(),
  unique(student_id, device_id) -- منع تكرار نفس الجهاز لنفس الطالب
);

-- =============================================
-- 3. CONTENT STRUCTURE (هيكل المحتوى)
-- =============================================

-- التصنيفات (مثال: الصف الأول، الصف الثاني)
create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  sort_order int default 0,
  created_at timestamp default now()
);

-- الكورسات
create table public.courses (
  id uuid default gen_random_uuid() primary key,
  category_id bigint references public.categories(id),
  title text not null,
  description text,
  thumbnail_url text,
  price decimal default 0, -- للعرض فقط
  is_published boolean default false,
  sort_order int default 0,
  created_at timestamp default now()
);

-- الباقات (تجميعة كورسات)
create table public.bundles (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  description text,
  thumbnail_url text,
  price decimal default 0, -- للعرض فقط
  is_published boolean default false,
  created_at timestamp default now()
);

-- ربط الكورسات بالباقات (Many-to-Many)
create table public.bundle_items (
  bundle_id uuid references public.bundles(id) on delete cascade,
  course_id uuid references public.courses(id) on delete cascade,
  primary key (bundle_id, course_id)
);

-- الفصول داخل الكورس
create table public.chapters (
  id uuid default gen_random_uuid() primary key,
  course_id uuid references public.courses(id) on delete cascade,
  title text not null,
  sort_order int default 0,
  created_at timestamp default now()
);

-- الدروس (فيديو، امتحان، ملف)
create table public.lessons (
  id uuid default gen_random_uuid() primary key,
  chapter_id uuid references public.chapters(id) on delete cascade,
  title text not null,
  type text check (type in ('video', 'exam', 'pdf')) default 'video',
  
  -- Video Details
  video_url text, -- Youtube ID or Bunny ID
  video_provider text default 'bunny', -- youtube, bunny, vimeo
  duration_minutes int default 0,
  
  -- Exam Details (لو الدرس امتحان)
  exam_questions jsonb, -- [{question: "...", options: [], answer: 1}]
  passing_score int default 50,
  allowed_attempts int default 0, -- 0 means unlimited
  
  -- Settings
  is_free_preview boolean default false, -- درس مجاني
  sort_order int default 0,
  created_at timestamp default now()
);

-- =============================================
-- 4. ACCESS & ACTIVATION (الاشتراكات والأكواد)
-- =============================================

-- جدول الاشتراكات النشطة
create table public.enrollments (
  id uuid default gen_random_uuid() primary key,
  student_id uuid references public.profiles(id) on delete cascade,
  
  -- الطالب ممكن يشترك في كورس مفرد أو باقة
  course_id uuid references public.courses(id) on delete cascade,
  bundle_id uuid references public.bundles(id) on delete cascade,
  
  activated_at timestamp default now(),
  expires_at timestamp, -- اختياري (لو الاشتراك بمدة)
  
  -- قيد: لازم حقل واحد منهم يكون مليان
  check (
    (course_id is not null and bundle_id is null) or 
    (course_id is null and bundle_id is not null)
  )
);

-- جدول أكواد التفعيل (الكروت)
create table public.activation_codes (
  code text primary key, -- الكود المطبوع (e.g. ZEYAD-2026-XYZ)
  type text check (type in ('course', 'bundle')) not null,
  target_id uuid not null, -- ID الكورس أو الباقة
  
  is_used boolean default false,
  used_by_student_id uuid references public.profiles(id),
  used_at timestamp,
  created_at timestamp default now()
);

-- =============================================
-- 5. PROGRESS & RESULTS (متابعة الطالب)
-- =============================================

-- متابعة مشاهدة الدروس
create table public.student_progress (
  student_id uuid references public.profiles(id) on delete cascade,
  lesson_id uuid references public.lessons(id) on delete cascade,
  is_completed boolean default false,
  last_position_seconds int default 0, -- وقف عند الدقيقة كام
  updated_at timestamp default now(),
  primary key (student_id, lesson_id)
);

-- نتائج الامتحانات
create table public.exam_results (
  id uuid default gen_random_uuid() primary key,
  student_id uuid references public.profiles(id) on delete cascade,
  lesson_id uuid references public.lessons(id) on delete cascade, -- الامتحان مرتبط بدرس
  score int not null,
  total_score int not null,
  attempt_number int default 1,
  is_passed boolean not null,
  details jsonb, -- تفاصيل الإجابات
  created_at timestamp default now()
);

-- =============================================
-- 6. BUSINESS LOGIC (الدالة السحرية)
-- =============================================

-- دالة تفعيل الكود (يتم استدعاؤها من التطبيق)
create or replace function redeem_code(code_input text)
returns jsonb language plpgsql security definer as $$
declare
  code_record record;
  user_id uuid := auth.uid();
begin
  -- 1. التحقق من وجود الكود
  select * into code_record from activation_codes 
  where code = code_input;

  if not found then
    return jsonb_build_object('success', false, 'message', 'الكود غير صحيح، تأكد من الكتابة');
  end if;

  if code_record.is_used then
    return jsonb_build_object('success', false, 'message', 'عفواً، هذا الكود تم استخدامه مسبقاً');
  end if;

  -- 2. التحقق من الاشتراك المسبق (لمنع تضييع الكود)
  if code_record.type = 'course' then
    if exists (select 1 from enrollments where student_id = user_id and course_id = code_record.target_id) then
      return jsonb_build_object('success', false, 'message', 'أنت مشترك بالفعل في هذا الكورس');
    end if;
    
    -- إضافة الاشتراك
    insert into enrollments (student_id, course_id) values (user_id, code_record.target_id);

  elsif code_record.type = 'bundle' then
    if exists (select 1 from enrollments where student_id = user_id and bundle_id = code_record.target_id) then
      return jsonb_build_object('success', false, 'message', 'أنت مشترك بالفعل في هذه الباقة');
    end if;

    -- إضافة الاشتراك
    insert into enrollments (student_id, bundle_id) values (user_id, code_record.target_id);
  end if;

  -- 3. حرق الكود
  update activation_codes 
  set is_used = true, used_by_student_id = user_id, used_at = now()
  where code = code_input;

  return jsonb_build_object('success', true, 'message', 'تم تفعيل الاشتراك بنجاح!');
end;
$$;

-- =============================================
-- 7. ROW LEVEL SECURITY (RLS) - الأمان
-- =============================================

-- تفعيل الـ RLS لكل الجداول
alter table profiles enable row level security;
alter table enrollments enable row level security;
alter table student_progress enable row level security;
alter table exam_results enable row level security;

-- قواعد الأمان (Policies)

-- 1. البروفايل: الطالب يشوف ويعدل بياناته فقط
create policy "Users can view own profile" on profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

-- 2. الاشتراكات: الطالب يشوف اشتراكات فقط
create policy "Users can view own enrollments" on enrollments for select using (auth.uid() = student_id);

-- 3. التقدم والنتائج: خاص بالطالب فقط
create policy "Users view own progress" on student_progress for all using (auth.uid() = student_id);
create policy "Users view own exam results" on exam_results for select using (auth.uid() = student_id);
create policy "Users insert exam results" on exam_results for insert with check (auth.uid() = student_id);

-- 4. المحتوى العام (الكورسات والباقات): متاح للجميع (للعرض في المتجر)
alter table courses enable row level security;
create policy "Public courses view" on courses for select using (true);
alter table bundles enable row level security;
create policy "Public bundles view" on bundles for select using (true);
alter table lessons enable row level security;
create policy "Public lessons view" on lessons for select using (true); -- (ممكن تقيدها لو حابب، بس الأسهل تخلي العناوين عامة والفيديو محمي في الفرونت)

-- =============================================
-- 8. TRIGGERS (أتمتة التواريخ)
-- =============================================
create trigger update_profiles_modtime before update on profiles 
for each row execute procedure update_updated_at_column();

create trigger update_progress_modtime before update on student_progress 
for each row execute procedure update_updated_at_column();

